### ISSUE TITLE
standalone crashes after a few hours of runtime

### ISSUE THREAD

**Issue by suchmememanyskill** [suchmememanyskill/SDH-CssLoader#82]
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 485, in finish_recv
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 489, in finish_recv
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 478, in <module>
  File "main.py", line 476, in run
  File "asyncio\base_events.py", line 628, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 595, in run_forever
  File "asyncio\base_events.py", line 1845, in _run_once
  File "asyncio\windows_events.py", line 439, in select
  File "asyncio\windows_events.py", line 819, in _poll
  File "asyncio\windows_events.py", line 88, in set_exception
asyncio.exceptions.InvalidStateError: invalid state

**Comment by suchmememanyskill** [comment]
I don't think this is an issue anymore. Have't experienced this since. Assuming this is fixed.
